import type { MetadataRoute } from 'next';

const BASE_URL = 'https://enjoy4game.com';

export default function sitemap(): MetadataRoute.Sitemap {
  const pages: MetadataRoute.Sitemap = [
    {
      url: BASE_URL,
      lastModified: '2026-05-15',
      changeFrequency: 'daily',
      priority: 1.0,
    },
    {
      url: `${BASE_URL}/guides`,
      lastModified: '2026-05-13',
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/games`,
      lastModified: '2026-05-22',
      changeFrequency: 'weekly',
      priority: 0.64,
    },
    {
      url: `${BASE_URL}/games/007-first-light`,
      lastModified: '2026-05-26',
      changeFrequency: 'daily',
      priority: 0.72,
    },
    {
      url: `${BASE_URL}/games/007-first-light/early-access-release-time`,
      lastModified: '2026-05-26',
      changeFrequency: 'daily',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/games/007-first-light/review-embargo`,
      lastModified: '2026-05-26',
      changeFrequency: 'daily',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/007-first-light/system-requirements`,
      lastModified: '2026-05-26',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/007-first-light/beginner-guide`,
      lastModified: '2026-05-26',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/project-mist`,
      lastModified: '2026-05-20',
      changeFrequency: 'daily',
      priority: 0.72,
    },
    {
      url: `${BASE_URL}/games/project-mist/release-date`,
      lastModified: '2026-05-20',
      changeFrequency: 'daily',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/games/project-mist/system-requirements`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/project-mist/multiplayer-co-op`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/project-mist/beginner-guide`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/project-mist/crashing-fix`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.66,
    },
    {
      url: `${BASE_URL}/games/project-mist/lockpick-chests`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.66,
    },
    {
      url: `${BASE_URL}/games/project-mist/train-door-key`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.66,
    },
    {
      url: `${BASE_URL}/games/project-mist/save-demo-transfer`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.66,
    },
    {
      url: `${BASE_URL}/games/project-mist/building-train-base`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.66,
    },
    {
      url: `${BASE_URL}/games/project-mist/is-it-worth-it`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.66,
    },
    {
      url: `${BASE_URL}/games/thick-as-thieves`,
      lastModified: '2026-05-20',
      changeFrequency: 'daily',
      priority: 0.72,
    },
    {
      url: `${BASE_URL}/games/thick-as-thieves/release-date`,
      lastModified: '2026-05-20',
      changeFrequency: 'daily',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/games/thick-as-thieves/solo-coop`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/thick-as-thieves/beginner-stealth-guide`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/thick-as-thieves/contracts-maps`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/thick-as-thieves/system-requirements`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/thick-as-thieves/gear-loadouts`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.66,
    },
    {
      url: `${BASE_URL}/games/thick-as-thieves/roadmap-console`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.66,
    },
    {
      url: `${BASE_URL}/games/thick-as-thieves/is-it-worth-it`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/zero-parades`,
      lastModified: '2026-05-21',
      changeFrequency: 'daily',
      priority: 0.72,
    },
    {
      url: `${BASE_URL}/games/zero-parades/release-date`,
      lastModified: '2026-05-21',
      changeFrequency: 'daily',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/games/zero-parades/beginner-guide`,
      lastModified: '2026-05-21',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/zero-parades/system-requirements`,
      lastModified: '2026-05-21',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/zero-parades/steam-deck`,
      lastModified: '2026-05-21',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/zero-parades/is-it-worth-it`,
      lastModified: '2026-05-21',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/mechanicus-ii`,
      lastModified: '2026-05-22',
      changeFrequency: 'daily',
      priority: 0.72,
    },
    {
      url: `${BASE_URL}/games/mechanicus-ii/release-date`,
      lastModified: '2026-05-22',
      changeFrequency: 'daily',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/games/mechanicus-ii/beginner-guide`,
      lastModified: '2026-05-22',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/mechanicus-ii/walkthrough`,
      lastModified: '2026-05-26',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/mechanicus-ii/factions`,
      lastModified: '2026-05-22',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/mechanicus-ii/system-requirements`,
      lastModified: '2026-05-22',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/mechanicus-ii/steam-deck-performance`,
      lastModified: '2026-05-22',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/mechanicus-ii/is-it-worth-it`,
      lastModified: '2026-05-22',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/romestead`,
      lastModified: '2026-05-25',
      changeFrequency: 'daily',
      priority: 0.72,
    },
    {
      url: `${BASE_URL}/games/romestead/release-date`,
      lastModified: '2026-05-25',
      changeFrequency: 'daily',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/games/romestead/beginner-guide`,
      lastModified: '2026-05-25',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/romestead/multiplayer-coop`,
      lastModified: '2026-05-25',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/romestead/system-requirements`,
      lastModified: '2026-05-25',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/romestead/is-it-worth-it`,
      lastModified: '2026-05-25',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/mina-the-hollower`,
      lastModified: '2026-05-20',
      changeFrequency: 'daily',
      priority: 0.72,
    },
    {
      url: `${BASE_URL}/games/mina-the-hollower/release-date`,
      lastModified: '2026-05-20',
      changeFrequency: 'daily',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/games/mina-the-hollower/system-requirements`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/mina-the-hollower/steam-deck`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/mina-the-hollower/beginner-guide`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/games/mina-the-hollower/is-it-worth-it`,
      lastModified: '2026-05-20',
      changeFrequency: 'weekly',
      priority: 0.68,
    },
    {
      url: `${BASE_URL}/directive-8020-overview`,
      lastModified: '2026-05-15',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/directive-8020-system-requirements`,
      lastModified: '2026-05-10',
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/directive-8020-release-time`,
      lastModified: '2026-05-10',
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/directive-8020-characters`,
      lastModified: '2026-05-12',
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/directive-8020-cast-actors`,
      lastModified: '2026-05-12',
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/directive-8020-review`,
      lastModified: '2026-05-15',
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/directive-8020-beginner-tips`,
      lastModified: '2026-05-12',
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/directive-8020-turning-points-story-tree`,
      lastModified: '2026-05-18',
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/directive-8020-movie-night-multiplayer`,
      lastModified: '2026-05-15',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/directive-8020-deluxe-edition`,
      lastModified: '2026-05-15',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/directive-8020-steam-deck`,
      lastModified: '2026-05-12',
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/directive-8020-community-questions`,
      lastModified: '2026-05-12',
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/directive-8020-death-scenes-guide`,
      lastModified: '2026-05-18',
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/directive-8020-stealth-guide`,
      lastModified: '2026-05-12',
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/directive-8020-collectibles-heirlooms`,
      lastModified: '2026-05-18',
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/directive-8020-o-death-secrets-curator`,
      lastModified: '2026-05-13',
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/directive-8020-crashing-fix`,
      lastModified: '2026-05-15',
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/directive-8020-all-endings`,
      lastModified: '2026-05-18',
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/directive-8020-cycle-13-explained`,
      lastModified: '2026-05-13',
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/directive-8020-how-long-to-beat`,
      lastModified: '2026-05-13',
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/directive-8020-how-to-save-everyone`,
      lastModified: '2026-05-13',
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/directive-8020-choices-consequences`,
      lastModified: '2026-05-18',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/directive-8020-mimic-detection-survival-guide`,
      lastModified: '2026-05-13',
      changeFrequency: 'weekly',
      priority: 0.88,
    },
    {
      url: `${BASE_URL}/directive-8020-trophy-guide`,
      lastModified: '2026-05-18',
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/directive-8020-trophy-list`,
      lastModified: '2026-05-13',
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/directive-8020-walkthrough`,
      lastModified: '2026-05-13',
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/directive-8020-little-star-walkthrough`,
      lastModified: '2026-05-13',
      changeFrequency: 'weekly',
      priority: 0.82,
    },
    {
      url: `${BASE_URL}/directive-8020-best-laid-plans-walkthrough`,
      lastModified: '2026-05-13',
      changeFrequency: 'weekly',
      priority: 0.82,
    },
    {
      url: `${BASE_URL}/directive-8020-the-sample-walkthrough`,
      lastModified: '2026-05-18',
      changeFrequency: 'weekly',
      priority: 0.82,
    },
    {
      url: `${BASE_URL}/directive-8020-dragnet-walkthrough`,
      lastModified: '2026-05-13',
      changeFrequency: 'weekly',
      priority: 0.82,
    },
    {
      url: `${BASE_URL}/directive-8020-mr-williams-walkthrough`,
      lastModified: '2026-05-13',
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/directive-8020-hostile-takeover-walkthrough`,
      lastModified: '2026-05-13',
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/directive-8020-revelation-walkthrough`,
      lastModified: '2026-05-13',
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/directive-8020-come-true-walkthrough`,
      lastModified: '2026-05-13',
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/about`,
      lastModified: '2026-05-12',
      changeFrequency: 'monthly',
      priority: 0.4,
    },
    {
      url: `${BASE_URL}/privacy-policy`,
      lastModified: '2026-05-12',
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${BASE_URL}/terms-of-use`,
      lastModified: '2026-05-12',
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${BASE_URL}/copyright-infringement`,
      lastModified: '2026-05-12',
      changeFrequency: 'yearly',
      priority: 0.3,
    },
  ];

  return pages;
}
